### ISSUE TITLE
Groups scalability?

### ISSUE THREAD

**Issue by sachinrekhi** [andrewgodwin/channels#106]
(Apologize for asking this here as it's more of a question than a bug, but wasn't sure if you had another forum yet for these types of questions like StackOverflow, etc)

The examples talk about using Groups as a mechanism for grouping a bunch of user reply channels and broadcasting a message to them (ie. classic chat room scenario).

However I'm planning on creating up to say 2 groups per active user (with group names like "user:<user_id>"). In this case each group would only actually have one added reply channel. I find it very easy to use groups to add reply channels to them during websocket connect and then throughout the rest of my http web requests to push content via those easily named groups.

My question is this a best practice? Since I'm going to have up to say 2 groups per actively connected user. Is there a scalability issue with having so many groups? (using redis channel layer, daphne web server, planning on putting nginx as reverse proxy in front of everything). Alternatively I could store reply channel names in my database and directly send to those via my http workflow which would be more work for me to manage, but possible if there is a groups scalability issue.

Thanks in advance for any insights!

**Comment by andrewgodwin** [comment]
(I don't look at Stack Overflow, so here is better than nothing I guess).

The short answer is, "I don't know". This code has only been through moderate-level load testing (up to around 1000 simultaneous connections), so its performance at true scale isn't yet known; that will only come from being deployed in a variety of different situations.

That said, given what I know of the Redis implementation what you're proposing should be absolutely fine; subscription-based groups with IDs in them (e.g. a per-user channel with ID like you're suggesting) are one of the patterns I specifically designed with in mind, and the hit on Redis from adding a group is very minor. If you were adding a group for each of, say, 200,000 users I'd suggest rethinking it a bit (or turning on sharded mode), because every group means a new redis sorted set key, but I think you should be fine.

You can also store the reply channel in your database; that's perfectly valid. You'll just need to write your own cleanup code.
