### ISSUE TITLE
Static is push to Channel Layer backend

### ISSUE THREAD

**Issue by vracheva** [andrewgodwin/channels#130]
When I use RedisChannelLayer as a backend for channels all static are sent to redis. What is purpose of this behavior?

**Comment by andrewgodwin** [comment]
What do you mean by static? Static files? Yes, they're run through the same system everything else is (they're just HTTP responses); in production, you would obviously use either varnish+whitenoise or nginx/apache in front to serve static files, since serving them from Django directly has never been scalable.
