### ISSUE TITLE
Log Server

### ISSUE THREAD

**Issue by eukreign** [andrewgodwin/channels#190]
I'm building a Docker based continuous integration & deployment service ([shipmaster](https://github.com/damoti/shipmaster)) and one of the critical features I need is showing live log output of what's going on: test runs, docker container builds, etc.

The way that I envision this is that a WebSocket would connect to a django channel and pass in the build number or some other task identifier and then I would stream the full log already written and thereafter continue streaming any new log events. It's possible that more than one client would want to view the same log file and they may connect to it at different times during the growth of the log file.

I'm trying to think of the best way to implement this with django channels.

Ideally if the `Group` object supported some kind of buffering then when I start a docker build I would just write the log to that `Group` (from celery task). After a build finishes I can delete the `Group` and from then on serve the log directly from file system via plain old Django (since the log file is no longer growing).

Is a buffering `Group` a good way to do this? Any suggestions on how to add such buffering to the `Group`?

Another option as suggested on IRC is to implement a separate log interface server. My understanding of how this would work is that the browser WebSocket would connect and trigger a message to the log interface channel requesting to subscribe to a specific log. The log interface server would keep track of individual reply channels and how much of the log has been sent to that reply channel so far and then send the full log or just new events as necessary.

To me the `Group` option seems like the simplest and better solution conceptually. I can see such a buffering `Group` being useful in other situations as well.

Any advice or suggestions on best way forward would be greatly appreciated. Thank you!

**Comment by andrewgodwin** [comment]
`Group` doesn't have buffering, and it would be near-impossible to add, since it would require a whole new data storage concept in the backend layers and brand new implementation code. In particular, you'd need something that had individual position pointers into a persistent event log per channel in the group, which is incredibly hard to do in a distributed fashion.

As such, keeping `Group` as it is now, a pure live broadcast mechanism, is my preferred solution.

The log interface server is the one I'd recommend; I see it working like this:
* You send a message to `logtail.start` containing the name of the log you wish to tail (either a path or some other identifier), and a channel name that lines in it should be sent to.
* The interface server listens on all files it's been told to, and whenever it gets a line, sends that line as a message to all channels that it got told to send it to in successive `start` messages. If it gets `ChannelFull` trying to send onto a channel, it just doesn't send that line.
* A message to `logtail.stop` with the file path and channel name removes that channel from getting any more messages.

Then, when a WebSocket connected, the handler would send a `start` message for the file it wished to tail, and pass in a custom channel name that had its own consumer inside django (log_line or something similar), which takes care of dispatching incoming lines into an appropriate `Group` (I'm imagining that multiple `start` messages are fine, so every connection sends one, even though an earlier one might have already started streaming that file to the local handler).

**Comment by eukreign** [comment]
I've reviewed the code for channels and daphne and I feel pretty comfortable with starting on a custom interface server but I'm a little confused about what you said in the last paragraph.

What did you mean by having multiple start messages but only one streaming file?

One of the requirements is that no matter when someone connects they get a copy of all previously written messages in addition to subsequent new messages. This means that it's possible two WebSockets connecting to the same log file (at different times) might be receiving different lines at a given time. WebSocket A which just connected might be catching up from the beginning with first line, while WebSocket B which has been connected since the beginning might just be idle or receiving line 100.

Theoretically WebSockets A & B might converge eventually on the same point in the log but I don't think it's necessary to handle this convergence. I think it would be simpler to open and tail the same file separately for each connection and not bother with `Group`.

Let me know if this workflow sounds correct:

- when the logtail interface starts it will create a channel: `channel_layer.new_channel("logtail.subscribe")`
- when a WebSocket connects to daphne it will route to a consumer which will subscribe this reply_channel by sending to `Channel("logtail.subscribe").send({'client': reply_channel, 'log': log_file})`
- the interface server will pickup the subscription after calling `channel_layer.receive_many(["logtail.subscribe"], block=False)`
- interface server will add client to subscribers list and also open the log file and start delivering lines from the log into the client reply_channel

Am I in the right ballpark?

**Comment by andrewgodwin** [comment]
So, the tricky thing is that if you make the log server send messages directly to the WebSocket reply_channel, they'll have to be in WebSocket reply format - that is, a dict with either the key `text` or the key `bytes` (which is doable, just means you need to be rigid)

Apart from that, yes, your solution is better.
