### ISSUE TITLE
Static files not being served automatically by separate worker on `DEBUG = True`

### ISSUE THREAD

**Issue by lemuelf** [andrewgodwin/channels#196]
When running the server and worker separately (`runserver --noworker` and `runworker`) during development (`DEBUG = True`), the worker doesn't automatically serve the staticfiles, which is the default django behavior.

However, running both server and worker in the same process (just `runserver`), also on `DEBUG = True` makes it serve staticfiles.

**Comment by thewayiam** [comment]
@andrewgodwin : looks like runworker command didn't has argument to specify worker to serve static files because [this line](https://github.com/andrewgodwin/channels/blob/master/channels/management/commands/runworker.py#L41), would you like to add argument for this case? If add argument it's reasonable to you, I would like to do it.

@lemuelf : for right now, you could add one routing rule for that in this case:
```
#routing.py
from channels import route
from channels.staticfiles import StaticFilesConsumer
# some other import
...

channel_routing = {
    ...
    # your routing settings
    ...
    route('http.request', StaticFilesConsumer()),
}
```

**Comment by andrewgodwin** [comment]
@thewayiam Yes, I'd like to make sure `runworker` serves staticfiles in debug mode; if you can make a pull request for that it'd be great.

**Comment by thewayiam** [comment]
@lemuelf : Would you also help to check this PR, thanks!

**Comment by andrewgodwin** [comment]
I just merged it into master; let me know if you have any issues and we can re-open this.

**Comment by lemuelf** [comment]
@thewayiam @andrewgodwin : master now works perfectly for me.  Thanks, guys.

**Comment by danni** [comment]
It would be nice to be able to turn this off in testing environments that are running with real setups (daphne, nginx, etc.) but still have DEBUG turned on.
