### ISSUE TITLE
URL Encoding Issue for Plus Symbol (%2B)

### ISSUE THREAD

**Issue by imaurer** [andrewgodwin/channels#210]
When using the "runserver" request handler and WSGI handler, this query gets handled properly (a=+one):

http://127.0.0.1:8000/test/?a=%2Bone

When I print from my test view:

```
def test(request):
    print request.GET, type(request)
```
I get the following using runserver without channels:

```
<QueryDict: {u'a': [u'+one']}> <class 'django.core.handlers.wsgi.WSGIRequest'>
```

However, when I turn on channels, I get the following with the same view function (note the SPACE before the one):

```
<QueryDict: {u'a': [u' one']}> <class 'channels.handler.AsgiRequest'>
```
It seems to have been inappropriately unencoded where something else down the Django line wants to do unencode again causing the space to appear. The issue seems to be with the message passed into AsgiHandler, but I am at a loss with where to go from there since I am new to Asgi.

Any help would be greatly appreciated.

thanks,
Ian

**Comment by andrewgodwin** [comment]
Ah, yes, this is probably because the Django request class tries to unencode things again where ASGI already decodes things before sending over the wire. I'll take a look at a fix soon.

**Comment by vikalpj** [comment]
@andrewgodwin I did a little bit of debugging and seems like https://github.com/andrewgodwin/channels/blob/56104e7fc62abd3cb816dd30f93e39a250873b36/channels/handler.py#L137 is the place where the parsing causes issues. Before this function is called every thing in the query params is already parsed from encoded values.

**Comment by andrewgodwin** [comment]
Okay, this fix actually involved Daphne and Channels, so make sure you have the new releases `daphne==0.12.2` and `channels==0.14.3`.

The asgi_redis serialization is to/from msgpack; nothing to do with this!

**Comment by vikalpj** [comment]
@andrewgodwin I don't think that would fix the things.
Like if i use a=%26ABC - url encoded value for `&ABC` then I should get  `&ABC` for query param a at the view level. But this fix doesn't handle that case and I get all the query dict to be {'a': [''], 'abc': ['']}....

So as i mentioned above the issue seems that we are trying to parse the values that are already parsed 

see the parsing example below
```
In [3]: http.QueryDict('a=%26ABC')
Out[3]: <QueryDict: {'a': ['&ABC']}>

In [4]: http.QueryDict('a=&ABC')
Out[4]: <QueryDict: {'a': [''], 'ABC': ['']}>
```

So As per the shared link above and my example the value of `self.message.get('query_string', '')` https://github.com/andrewgodwin/channels/blob/56104e7fc62abd3cb816dd30f93e39a250873b36/channels/handler.py#L137  should be `a=%26ABC` but the actual value received here is `a=&ABC`... /

May be msgpack might be converting that, but I haven't used msg pack before so can't comment. but i guess this analysis can help to fix this issue :)

**Comment by vikalpj** [comment]
Also `%25` seems to change my data as well like if i enter %252912 so the data i should receive is %2912 but i receive data as )12 as `%29` gets converted to `)`

**Comment by andrewgodwin** [comment]
The problem is that ASGI represents the query string as already-url-decoded unicode, while Django is expecting to try and urldecode it, so double decoding is happening. My fix specifically fixed + but not &; I'll take another look and maybe just make query string undecoded bytes.

**Comment by andrewgodwin** [comment]
OK, switched query strings to be entirely handled by Django, and released channels 0.15 and Daphne 0.13 (you'll need to upgrade both). Can't seem to break it with + and & now.

**Comment by ssteinerx** [comment]
@vikalpj Can you provide specific URLs that failed so we can get a test in for this?

**Comment by vikalpj** [comment]
@andrewgodwin The things seems to be working now. Thanks  👍.
@ssteinerx So the url where I encountered this issue was like,  /path?data=abc%2Bxyz so my data value here was abc+xyz.

**Comment by mTatcher** [comment]
Still having this issue on channels 0.17.3 and daphne 0.15.0 when trying to parse 

"ws://localhost:8000/my_route/?token=Za02Ezc5hz%2F5dMoWxJo8Vgk4Op%2BF6NGlcRoHPpenuT3rKCQaWxs6uKnsHAltSZ5Pxte%2FnQIoxjwfkHPnjAoF%2Bw%3D%3D"

I get '+' signs in message.content.query_string and spaces in AsgiRequest(message)'s GET instead of '+' signs

**Comment by andrewgodwin** [comment]
If you're looking at raw message contents you're going to see + signs as the `query_string` is not urldecoded (that's what the fix was). Django runs urldecode on the query string so by the time you see it in `request.GET` it has spaces as expected.
