### ISSUE TITLE
Stateful connections?

### ISSUE THREAD

**Issue by jlafon** [andrewgodwin/channels#276]
Hello, and thank you for making this project! My question is this: Will channels eventually support stateful connections? 

I found this statement in the [excellent documentation](http://channels.readthedocs.io/en/latest/getting-started.html#persisting-data): 

> Channels is network-transparent and can run on multiple workers, so you can’t just store things locally in global variables or similar.

I'm currently using Tornado's [WebSocketHandler](http://www.tornadoweb.org/en/stable/websocket.html?highlight=websockethandler#tornado.websocket.WebSocketHandler) for websockets (hackily integrated with Django) and Django for all else. The websocket handler performs an I/O expensive step when a connection is opened, but can respond to messages received over the websocket quickly afterward. It seems as though using channels for my use case would require this expensive step to be performed for each message received.

**Comment by andrewgodwin** [comment]
Channels' design deliberately prevents you from having local state on connections, since it's inherently difficult to scale unless all your connections are exactly equal. Instead, `channel_session` is provided, which uses the Django session framework to allow you to persist things against sockets, so you can do things at connection or during a message receive and retrieve them later.

It does not, however, help you if the thing you're doing to a socket state is inherently local, such as opening a subprocess or a local file; if that's the case, Channels is likely the wrong design for you and you need to go another route and sticky WebSockets to custom local processes, and design your own broadcast/inter-node routing system.
