### ISSUE TITLE
Channel name on RouteClass

### ISSUE THREAD

**Issue by AMontagu** [andrewgodwin/channels#279]
Hi,

Just trying to implement class based channels and got stuck on adding a channel name for accesing it from my backend django application. (client side work well)

So I have an inherited JsonWebsocketConsumer class based channel : 

```
class MyConsumer(JsonWebsocketConsumer):
    # Set to True if you want them, else leave out
    strict_ordering = False
    slight_ordering = False

    def connection_groups(self, **kwargs):
        print("connection groups json")
        return ["test"]

    def connect(self, message, **kwargs):
        print("connect json")
        pass

    def receive(self, content, **kwargs):
        print("receive json :")
        print(content)
        self.send(content)

    def disconnect(self, message, **kwargs):
        print("disconnect json")
        pass
```

and a simple routing like in the doc : 
`channel_routing = [
    route_class(MyConsumer, path=r"^/test/"),
]`

Now when I do in a traditional view : 

`Channel('test').send({'4': 5, '6': 7})`

Nothing happen.

I was trying to figure out what is the name of the channel and I found this file : 
(https://github.com/andrewgodwin/channels/blob/master/channels/routing.py)[https://github.com/andrewgodwin/channels/blob/master/channels/routing.py]

After that I have understand the big part that RouteClass inherit from Route and give it an array of name taken from the BaseConsumer class that return the key of method_mapping.

Now I can't figure out what override because in WebsocketConsumer this is commented that we are not supposed to override method_mapping but in the documentation this is the way for doing what I want when used BaseConsumer.

What I have trying: 

### override method_mapping in MyConsumer : 

```
method_mapping = {
    "websocket.connect": "raw_connect",
    "websocket.receive": "raw_receive",
    "websocket.disconnect": "raw_disconnect",
    "test": "method_name",
    "websocket.test": "method_name",
} 

def method_name(self, message, **kwargs):
    print("receive json :")
    print(message)
    self.send(message)
```

### override channel_names in MyConsumer :

```
@classmethod
def channel_names(cls):
    print("channel_names")
    map = {
        "websocket.connect": "raw_connect",
        "websocket.receive": "raw_receive",
        "websocket.disconnect": "raw_disconnect",
        "test": "method_name",
        "websocket.test": "method_name",
    }
    return set(map.keys())
```

So maybe add a way to add custom channels name in WebSocket inherited class or tell me what I miss.

**Comment by andrewgodwin** [comment]
WebSockets only ever come in on the predefined channels `websocket.connect` and `websocket.receive` - you're trying to override a WebSocket consumer but send on a non-websocket channel, which makes no sense.

If you want to use WebSockets, you should connect in via a WebSocket client and do things that way.

If you want to use a custom channel, use BaseConsumer, not WebsocketConsumer.

**Comment by AMontagu** [comment]
So if I have a background process in my server and want tu push some data to client when the process return somme result. Do I need to implement a BaseConsumer ? 

How then I connect a js client to the custom channels ? 

The other way, that I think is more WebSocket friendly, is to created a group and when I need I create a websocket that push data to the group. But how send a message to the group from a python code ?

What are the best way to do that ? Group or custom channel ?

One of the big point of Websocket is for sending data to client from the server and there is no exemple of that in the documentation. How can we use the send function outside the class and without a channel name ? I think when you use websocket for a while is obvious but not for me. Even if I have read hours on that. 

The obvious way that working good is to send data on the channel websocket.receive in my code python and then do process data with a simple handler but I wanted to use the JsonWebSocket class based channels because I will have a lot of background process talking with different type of client and doing all the work with conditional test on receive data will look very ugly.

**Comment by andrewgodwin** [comment]
* To send data without a channel name you use a Group. Add your WebSockets to a group on connect and then send things you want to send to them to groups.

* To get results from an external process, you'll need to write custom async code. Channels is event-driven, and unless you have some Python code already wrapping the process that can generate the events (messages), you need one.

* You can send to a Group or Channel from any Python code. Just import the `channel_layer` object from the `asgi.py` file mentioned in the deployment docs, and call the low-level ASGI methods `.send` and `.send_group` on them.

**Comment by AMontagu** [comment]
Thank for your answer. I will try to use the low-level methods. 

If I can't I will just use send data on websocket.receive channel and make conditional action from data received from sending data to the correct group..

**Comment by SteveByerly** [comment]
Sorry to re-open this issue, but I felt it better than making a new issue. I just ran into, what I believe, to be the same hurdle as @AMontagu 

I wanted to make my own `JsonWebsocketConsumer` class to see how it works, and add my own custom methods to handle certain actions. I'm using the "multichat" example app as a working model to base my project on.

**consumers.py**
```
class ChatWSConsumer(JsonWebsocketConsumer):
    http_user = True

    method_mapping = {
        'websocket.connect': 'raw_connect',
        'websocket.receive': 'raw_receive',
        'websocket.disconnect': 'raw_disconnect',
        'chat.join': 'chat_join',
        'chat.leave': 'chat_leave',
        'chat.send': 'chat_send',
    }

    def receive(self, content, **kwargs):
        content['reply_channel'] = self.message.content['reply_channel']
        channel = 'chat.%s' % content['command']
        Channel(channel).send(content)
```


**chat routing.py**

```
websocket_routing = [
    route_class(consumers.ChatWSConsumer),
]
```

**project routing.py**

```
channel_routing = [
    route('http.request', consumers.http_consumer, path=r'/http_consumer/$'),
    include('chat.routing.websocket_routing', path=r'^/chat/$'),
]
```

I naively assumed that all I had to do was add the extra channel_name:method_name mappings to `method_mapping`

With this setup `Channel(channel).send(content)` doesn't work and produces the following error:
`ERROR - worker - Could not find match for message on chat.join! Check your routing.`

The reason for this error is that there is no `path` set in my content, so this check fails in `routing.py`:
https://github.com/django/channels/blob/0.17.2/channels/routing.py#L216

To fix this, I needed to add `path` to my `content` dict:

```
def receive(self, content, **kwargs):
    content['reply_channel'] = self.message.content['reply_channel']
    content['path'] = self.path # Set this so that the routing works correctly
    channel = 'chat.%s' % content['command']
    Channel(channel).send(content)
```

In hindsight, it makes perfect sense why it didn't work. The routing rules need to match all the arguments for the route, so if you don't supply them, then it won't route. However, it took awhile (and dropping to pdb in the channels code) to really figure out where the issue was.

I went back to the documentation after figuring this out, and I guess I see it explained, but I didn't catch on when working through trying to solve the problem.

I'm not sure how troublesome this is for others, but perhaps making the error more specific would help? In the spirit of:
`Could not find match for message on chat.join! Check your routing - you may have failed to include the required filter parameters for the desired route.`

**Comment by AMontagu** [comment]
Like @andrewgodwin said channels and websockets are not designed like that. 

What you need to do if send data to group in connect, receive or disconnect action.

this can help you : 

```
class ChatConsumer(JsonWebsocketConsumer):
	http_user = True

	def connection_groups(self, **kwargs):
		print("connection to a chat")
		chatName= kwargs["ChatName"]
		nameGroup = "chat" + str(chatName)
		print(nameGroup)
		return [nameGroup]

	def connect(self, message, **kwargs):
		print("connect chat")
                chatName= kwargs["ChatName"]
		nameGroup = "chat" + str(chatName)
		text = json.dumps({
				"action": "join",
			})
		Group("nameGroup").send({
			"text": text,
		})

	def receive(self, content, **kwargs):
		print("receive chat")
		print(content)
                chatName= kwargs["ChatName"]
		nameGroup = "chat" + str(chatName)
		text = json.dumps({
				"action": "message",
				"user": self.message.user.username,
				"authenticated": self.message.user.is_authenticated(),
				"message": content["text"],
			})
		Group(nameGroup).send({
			"text": text,
		})

	def disconnect(self, message, **kwargs):
		print("disconnect chat")
                chatName= kwargs["ChatName"]
		nameGroup = "chat" + str(chatName)
		text = json.dumps({
				"action": "disconnect",
			})
		Group(nameGroup).send({
			"text": text,
		})
```

With this for routing:

`route_class(ChatConsumer, path=r"^/chat/(?P<ChatName>[0-9A-Za-z]+)/")`

**Comment by andrewgodwin** [comment]
The problem here is, as you said, the `path` prefix on the routing. It's probably cleaner to split it into two class based consumers, one for WebSocket consumption and one for command handling, and then have two routing entries, one with a path prefix (websocket one) and one without (command handler).

**Comment by SteveByerly** [comment]
Thanks @andrewgodwin that's what I ended up doing. Still needed to add the extra data to route, though.
