### ISSUE TITLE
Sending content dict with more keys than single 'text' causes channels to fail silently

### ISSUE THREAD

**Issue by anton-white** [andrewgodwin/channels#289]
Tried to send a content like this:
```
Group('chat-hi').send({'text': 'Nice!', 'a': 1})
```

and it made channels to stop responding at all.
I may be missing something obvious, but it looks like channels fail silently without any exception.

**Comment by andrewgodwin** [comment]
Daphne should be printing errors when that happens. Are you running `runserver` or `daphne` separately?

**Comment by anton-white** [comment]
`runserver` at the moment

**Comment by andrewgodwin** [comment]
Hmm, it's possible that it's not logging correctly then. I'll investigate later.

**Comment by anton-white** [comment]
thanks!
BTW, do you receive notifications about updates in closed issues?
I faced today some interesting issue and described it in: https://github.com/andrewgodwin/channels/issues/236

**Comment by andrewgodwin** [comment]
I did - I'll describe what that is over there.

**Comment by anton-white** [comment]
Thank you!

**Comment by pirate** [comment]
Also getting this issue on my machine, I've updated all my requirements (except Twisted which I've kept frozen at 16.2 as recommended).

It only occurs when there are more keys than `{'text': 'some text'}`.  `Channel`s work fine otherwise, it just seems to be happening when using `Group`s.  I thought `Group`s were broken entirely until I found this thread and tried deleting my other key:vals and only using `text`, at which point it started working immediately.

**Comment by pirate** [comment]
Part of my confusion is that `Channel` and `Group` take a dictionary expecting `{'text': ''}` or `{'bytes': ''}` instead of a keyword argument `text=`/`bytes=`, so I assumed when passed a dict it would dump the dictionary to JSON to send the resulting string over the wire.  Out of curiosity, why was the design chosen to take a dictionary instead of named arguments?

**Comment by andrewgodwin** [comment]
The Channel/Group system is generic, and not just for WebSockets - thus, it accepts any "message", which is a dictionary (there's a spec at http://channels.readthedocs.io/en/latest/asgi.html).

This means that the server which consumes the messages is responsible for erroring out when they don't meet the WebSocket specification. Daphne has code to do this but it's being swallowed - I'm in the middle of fixing it to print to the console during `runserver` right now.

**Comment by andrewgodwin** [comment]
Alright, I've fixed the error catching so it a) doesn't hang Twisted when it happens and b) prints to the console during `runserver`, like this:

```
[2016/08/06 05:16:58] WebSocket CONNECT /frontend/ [127.0.0.1:53739]
2016-08-06 05:16:58,831 - ERROR - server - HTTP/WS send decode error: Got invalid WebSocket reply message on websocket.send!mZXqOkrHeETS - contains unknown keys {'badkeyname'}
```

It'll be out in the next release pair of Daphne/Channels (I'll make Channels depend on the new Daphne version so you'll get both with an upgrade)

**Comment by pirate** [comment]
Thanks for the explanation and incredibly quick fix @andrewgodwin!
