### ISSUE TITLE
Messagepack support?

### ISSUE THREAD

**Issue by paurullan** [andrewgodwin/channels#37]
Just for the conversation and to poll interest, would it be possible to allow the use of messagepack as an alternative to json encoding?
http://msgpack.org/

Messagepack (or `msgpack`) is a compact json protocol where values like `true` or «file element list» are encoded so the final and global value size is reduced.

There is a good python encoder and it could improve channel performance overall.

I will consider doing this myself but I would love some feedback to know if it is interesting or just some crazy idea.

**Comment by andrewgodwin** [comment]
We've evaluated msgpack at work and I just don't think it offers enough over JSON to be reasonable - the encoding/decoding is often slower, the language support is much poorer, and in general I'd rather just have one version of a standard, especially since there's plans to write parts of the Channels system in other languages.

That said, at some point it's up to the individual channel backend to support whatever it likes, as long as it spits out dicts at either end, so this is something that could be implemented by someone else as a pluggable backend to see, but I don't see the main project going that way, so I'm going to close this for now. We might always come back and revisit this if message size/bandwidth turns out to be a limiting factor, though.
