### ISSUE TITLE
Tests fail.

### ISSUE THREAD

**Issue by DanLipsitt** [andrewgodwin/channels#66]
Running `tox` from the commandline or Travis CI results in failures in most or all python/django version combinations.

See https://travis-ci.org/DanLipsitt/channels/builds/102221657 for log.

I've submitted PR #65 to create a Travis config for the project so these issues are more visible.

**Comment by andrewgodwin** [comment]
Yes, the tests aren't done yet, and won't be until the code is semi-finalised; closing as INVALID, since obviously passing tests are needed, and will come when the code stablilises.

**Comment by DanLipsitt** [comment]
Context: I'm seeing if I can make a dent in #32 because that's a blocker for me. Writing my own tests is a way for me to explore the problem, and might be helpful for the project in general. So it would be useful to have a working test _command_ even if existing tests don't pass. Currently they are not just failing, but erroring.

**Comment by DanLipsitt** [comment]
I'll see if I can get the test runner working unless you recommend against it. Any tips?

**Comment by andrewgodwin** [comment]
Not really; what's there is pretty basic and doesn't really work terribly well. The main problem you'll have is that tests will need to have at least two different processes running if not three (daphne, redis, test code) if you want to do proper end-to-end testing; if you just want to artificially generate messages instead of going via Daphne, you'll need to probably write a whole suite of code that makes example messages and hook everything up to the in-memory ASGI backend.

**Comment by DanLipsitt** [comment]
I'm not trying to test end-to-end. Just unit testing. I think I may have uncovered a bug already, or I am using the wrong Message class. I'll put it in a PR so you can see. Then I'll probably put Channels aside until things have settled a bit more. Thanks!
