### ISSUE TITLE
Is there a way to list open channel sessions?

### ISSUE THREAD

**Issue by Charlex** [andrewgodwin/channels#77]

**Comment by andrewgodwin** [comment]
No - if you read the docs, channels does deliberately not keep track of "open" channel sessions, as doing so is a lot of overhead in a distributed system. If you want to do this, you can manually keep track of things in the various handlers (e.g. for websockets, add something to a table in a `websocket.connect` handler, and remove it either in a `websocket.disconnect` handler or after a certain timeout, since channels only 99.99% guarantees that `disconnect` gets called)

**Comment by Charlex** [comment]
Thanks Andrew for adding to my understanding. I've read the docs, but I don't think the exact nature of channels states sunk in for me. Appreciate it!
